version: '3.9'

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: eventos_db
      MYSQL_USER: usereventos
      MYSQL_PASSWORD: passeventos
      MYSQL_ROOT_PASSWORD: root
    networks:
      - eventos-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  eventosapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - eventos-net

networks:
  eventos-net:
    name: eventos-net

volumes:
  mysql-data: