micronaut:
  application:
    name: eventosapp
  server:
    port: ${SERVER_PORT:8080}

datasources:
  default:
    url: jdbc:mysql://mysqldb:3306/eventos_db?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: usereventos
    password: passeventos
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: MYSQL

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration