micronaut:
  application:
    name: eventosapp
  server:
    port: 8080
datasources:
  default:
    url: jdbc:mysql://localhost:3307/${MYSQL_DATABASE:eventos_db}?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:usereventos}
    password: ${MYSQL_PASSWORD:passeventos}
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: MYSQL

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration